/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.itextpdf.text.DocumentException;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Desktop;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel
 */
public class TelaPrincipal_GUI extends javax.swing.JFrame {

    static int cod;
    static String nom;
    static String cpf;
    static String cel;
    static String sala;
    static String dataReserva;
    static String inicio;
    static String fim;
    String url = "jdbc:mysql://localhost/godear"; // enderço do BD
    String username = "root";        //nome de um usuário de seu BD
    String password = "";  // senha do BD
    
    public static DefaultTableModel reservas(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("ID");
            columnNames.addElement("Nome");
            columnNames.addElement("Cpf");
            columnNames.addElement("Cel");
            columnNames.addElement("Sala");
            columnNames.addElement("Data");
            columnNames.addElement("Inicio");
            columnNames.addElement("Fim");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }
    
    public static DefaultTableModel reservas1(ResultSet rs) {
        try {
           ResultSetMetaData metaData = rs.getMetaData();
         int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
       // AS LINHAS ABAIXO SÃO REFERENTES AOS CAMPOS DA TABELA CLIENTE
            columnNames.addElement("Sala");
            columnNames.addElement("Data");
            columnNames.addElement("Inicio");
            columnNames.addElement("Fim");
         
            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
           return new DefaultTableModel(rows, columnNames);
       } catch (Exception e) {

           return null;
        }
        }
    
    
    public void refresh(){
    
        try{
           Connection conn;
                  conn = (Connection) DriverManager.getConnection(url, username, password);
            Controller.conexaoBanco.carregaDriver();

            System.out.println("realizado");
                    String sql = "SELECT * FROM reservas;";
        java.sql.PreparedStatement pst = (java.sql.PreparedStatement) conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        View.TelaPrincipal_GUI.tabelaConsultar.setModel(reservas(rs));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }    
            } 
    
    public void refresh1(){
    
        try{
           Connection conn;
                  conn = (Connection) DriverManager.getConnection(url, username, password);
            Controller.conexaoBanco.carregaDriver();

            System.out.println("realizado");
                    String sql = "SELECT sala_res, data_res, inicio_res, fim_res FROM reservas;";
        java.sql.PreparedStatement pst = (java.sql.PreparedStatement) conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        View.TelaPrincipal_GUI.tabelaReservar.setModel(reservas1(rs));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }    
            } 
    
    
    public TelaPrincipal_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("godear?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        reservasQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Reservas r");
        reservasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : reservasQuery.getResultList();
        reservasQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Reservas r");
        reservasList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : reservasQuery1.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultar = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cod2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sala1 = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        cpf1 = new javax.swing.JFormattedTextField();
        cel1 = new javax.swing.JFormattedTextField();
        data1 = new javax.swing.JFormattedTextField();
        inicio1 = new javax.swing.JFormattedTextField();
        fim1 = new javax.swing.JFormattedTextField();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();
        buttonAction3 = new org.edisoncor.gui.button.ButtonAction();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nomeReserva = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaReservar = new javax.swing.JTable();
        salaReserva = new javax.swing.JComboBox<>();
        inicioReserva = new javax.swing.JFormattedTextField();
        fimReserva = new javax.swing.JFormattedTextField();
        cpfReserva = new javax.swing.JFormattedTextField();
        celReserva = new javax.swing.JFormattedTextField();
        data = new javax.swing.JFormattedTextField();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jPanel1 = new javax.swing.JPanel();
        Declaracao = new javax.swing.JButton();
        buttonAction2 = new org.edisoncor.gui.button.ButtonAction();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cod3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jPanel5 = new javax.swing.JPanel();
        buttonAction5 = new org.edisoncor.gui.button.ButtonAction();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(153, 252, 175));
        jPanel2.setLayout(null);

        buttonAction1.setText("X");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonAction1);
        buttonAction1.setBounds(630, 400, 50, 35);

        tabelaConsultar.setBackground(new java.awt.Color(240, 240, 240));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, reservasList1, tabelaConsultar);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idRes}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeRes}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpfRes}"));
        columnBinding.setColumnName("Cpf");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${celRes}"));
        columnBinding.setColumnName("Cel ");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${salaRes}"));
        columnBinding.setColumnName("Sala");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataRes}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${inicioRes}"));
        columnBinding.setColumnName("Inicio");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fimRes}"));
        columnBinding.setColumnName("Fim");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabelaConsultar);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 680, 210);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Código : ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 230, 60, 20);
        jPanel2.add(cod2);
        cod2.setBounds(90, 230, 200, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("CPF:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 320, 60, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Celular:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 350, 60, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Sala (reservada):");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(300, 260, 120, 20);
        jPanel2.add(sala1);
        sala1.setBounds(420, 260, 130, 20);

        btnConsultar.setText("Consulta");
        btnConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultar);
        btnConsultar.setBounds(560, 260, 100, 30);

        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar);
        btnAlterar.setBounds(560, 300, 100, 30);

        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluir);
        btnExcluir.setBounds(560, 340, 100, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Data da reserva:");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(300, 290, 120, 20);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Inicio Reserva:");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(300, 320, 120, 20);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Fim Reserva:");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(300, 350, 120, 20);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Nome:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 290, 60, 20);
        jPanel2.add(nome1);
        nome1.setBounds(90, 290, 200, 20);

        try {
            cpf1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(cpf1);
        cpf1.setBounds(90, 320, 200, 20);

        try {
            cel1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(cel1);
        cel1.setBounds(90, 350, 200, 20);

        try {
            data1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(data1);
        data1.setBounds(420, 290, 130, 20);

        try {
            inicio1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(inicio1);
        inicio1.setBounds(420, 320, 130, 20);

        try {
            fim1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(fim1);
        fim1.setBounds(420, 350, 130, 20);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel2.add(panelImage2);
        panelImage2.setBounds(0, -30, 680, 470);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel8.setBackground(new java.awt.Color(153, 252, 175));
        jPanel8.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("CPF:");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(50, 270, 60, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Realizar reserva de sala");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(240, 180, 235, 56);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Sala:");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(50, 330, 60, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Data da reserva:");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(400, 240, 120, 20);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Horário início:");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(420, 280, 100, 20);

        btnReserva.setText("Reservar");
        btnReserva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });
        jPanel8.add(btnReserva);
        btnReserva.setBounds(190, 380, 100, 30);

        buttonAction3.setText("X");
        buttonAction3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction3ActionPerformed(evt);
            }
        });
        jPanel8.add(buttonAction3);
        buttonAction3.setBounds(630, 400, 50, 35);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Horário fim:");
        jPanel8.add(jLabel30);
        jLabel30.setBounds(420, 320, 100, 20);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Nome:");
        jPanel8.add(jLabel32);
        jLabel32.setBounds(50, 240, 60, 20);
        jPanel8.add(nomeReserva);
        nomeReserva.setBounds(110, 240, 269, 20);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Celular:");
        jPanel8.add(jLabel33);
        jLabel33.setBounds(50, 300, 60, 20);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, reservasList, tabelaReservar);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${salaRes}"));
        columnBinding.setColumnName("Sala");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataRes}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${inicioRes}"));
        columnBinding.setColumnName("Inicio");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fimRes}"));
        columnBinding.setColumnName("Fim");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tabelaReservar);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(30, 10, 630, 170);

        salaReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informática", "Salão de Festas", "Auditório", "Informática Superior", "Auditório Superior", "Laboratório Mecânico" }));
        jPanel8.add(salaReserva);
        salaReserva.setBounds(110, 330, 127, 20);

        try {
            inicioReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inicioReserva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicioReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inicioReserva.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inicioReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioReservaActionPerformed(evt);
            }
        });
        jPanel8.add(inicioReserva);
        inicioReserva.setBounds(520, 280, 80, 30);

        try {
            fimReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fimReserva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fimReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fimReserva.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fimReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fimReservaActionPerformed(evt);
            }
        });
        jPanel8.add(fimReserva);
        fimReserva.setBounds(520, 320, 80, 30);

        try {
            cpfReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel8.add(cpfReserva);
        cpfReserva.setBounds(110, 270, 270, 20);

        try {
            celReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel8.add(celReserva);
        celReserva.setBounds(110, 300, 270, 20);

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        data.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        jPanel8.add(data);
        data.setBounds(520, 240, 80, 30);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel8.add(panelImage1);
        panelImage1.setBounds(0, -30, 680, 470);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reservar", jPanel7);

        jPanel1.setBackground(new java.awt.Color(153, 252, 175));
        jPanel1.setLayout(null);

        Declaracao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Declaracao.setText("Gerar Declaração");
        Declaracao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Declaracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclaracaoActionPerformed(evt);
            }
        });
        jPanel1.add(Declaracao);
        Declaracao.setBounds(70, 100, 199, 53);

        buttonAction2.setText("X");
        buttonAction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction2ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAction2);
        buttonAction2.setBounds(629, 392, 51, 35);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gerar Relatório");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 40, 220, 50);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gerar Declaração");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 40, 280, 50);

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Gerar Relatório");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(400, 100, 200, 50);
        jPanel1.add(cod3);
        cod3.setBounds(330, 190, 190, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Para qual ID fazer a declaração: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 190, 220, 30);

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage3);
        panelImage3.setBounds(0, -30, 680, 470);

        jTabbedPane1.addTab("Relatório", jPanel1);

        jPanel5.setBackground(new java.awt.Color(153, 252, 175));
        jPanel5.setLayout(null);

        buttonAction5.setText("X");
        buttonAction5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction5ActionPerformed(evt);
            }
        });
        jPanel5.add(buttonAction5);
        buttonAction5.setBounds(630, 392, 50, 35);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Aba de Consultas");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(50, 30, 160, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Abrir PDF");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(60, 70, 110, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Aba de Reservas");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(290, 30, 160, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Abrir PDF");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(290, 70, 110, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Aba de Relatório");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(520, 30, 160, 30);

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("Abrir PDF");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(520, 70, 110, 40);

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel5.add(panelImage4);
        panelImage4.setBounds(0, -30, 680, 470);

        jTabbedPane1.addTab("HELP", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(685, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja sair do programa?", "Sair do programa",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao==0){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void buttonAction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction2ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja sair do programa?", "Sair do programa",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao==0){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonAction2ActionPerformed

    private void DeclaracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclaracaoActionPerformed
        try {
            // Gerador de relatórios
            Model.PdfDeclaracao_DAO.Relatorio();
        } catch (DocumentException ex) {
            Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_DeclaracaoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
       
        Model.Consultar_DAO.Consultar();
        refresh();
        refresh1();
    
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja realmente alterar esses dados da reserva/usuário?", "Alterar dados usuário/reserva",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao==0){
            Model.Consultar_DAO.Alterar();
        }
        refresh();
        refresh1();

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja realmente excluir esses dados da reserva/usuário?", "Ecluir dados usuário/reserva",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao==0){
            Model.Consultar_DAO.Excluir();
        }
        refresh();
        refresh1();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void buttonAction5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction5ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja sair do programa?", "Sair do programa",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao==0){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonAction5ActionPerformed

    private void buttonAction3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction3ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja sair do programa?", "Sair do programa",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao==0){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonAction3ActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        Model.Reservar_DAO.Reservar();
        refresh();
        refresh1();
    }//GEN-LAST:event_btnReservaActionPerformed

    private void inicioReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioReservaActionPerformed

    private void fimReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fimReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fimReservaActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Process exec = Runtime.getRuntime().exec("cmd /C start https://drive.google.com/file/d/1h-ivNuuTa2L-ddGhaAHKkjXR6zU4gDwO/view?usp=share_link");
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Process exec = Runtime.getRuntime().exec("cmd /C start https://drive.google.com/file/d/1J54WkQyTLZ2MucjUH_8lNW2VKU0vxfJV/view?usp=share_link");
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Process exec = Runtime.getRuntime().exec("cmd /C start https://drive.google.com/file/d/1kMPGqn0aKT9dstN7uVhdee8nqR86H-K8/view?usp=share_link");
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Model.PdfReserva_DAO.Relatorio();
        } catch (DocumentException ex) {
            Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Declaracao;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnReserva;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonAction buttonAction2;
    private org.edisoncor.gui.button.ButtonAction buttonAction3;
    private org.edisoncor.gui.button.ButtonAction buttonAction5;
    public static javax.swing.JFormattedTextField cel1;
    public static javax.swing.JFormattedTextField celReserva;
    public static javax.swing.JTextField cod2;
    public static javax.swing.JTextField cod3;
    public static javax.swing.JFormattedTextField cpf1;
    public static javax.swing.JFormattedTextField cpfReserva;
    public static javax.swing.JFormattedTextField data;
    public static javax.swing.JFormattedTextField data1;
    private javax.persistence.EntityManager entityManager;
    public static javax.swing.JFormattedTextField fim1;
    public static javax.swing.JFormattedTextField fimReserva;
    public static javax.swing.JFormattedTextField inicio1;
    public static javax.swing.JFormattedTextField inicioReserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField nome1;
    public static javax.swing.JTextField nomeReserva;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private java.util.List<View.Reservas> reservasList;
    private java.util.List<View.Reservas> reservasList1;
    private javax.persistence.Query reservasQuery;
    private javax.persistence.Query reservasQuery1;
    public static javax.swing.JTextField sala1;
    public static javax.swing.JComboBox<String> salaReserva;
    public static javax.swing.JTable tabelaConsultar;
    public static javax.swing.JTable tabelaReservar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
